library.library_action.*:
  type: config_entity
  label: 'Library action config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    action:
      type: integer
      label: 'Status change'
    uuid:
      type: string
